[book]
authors = ["mfontanini"]
language = "en"
multilingual = false
src = "src"
title = "Presenterm documentation"

[preprocessor]

[preprocessor.catppuccin]
assets_version = "2.1.0" 

[output]

[output.html]
additional-css = ["./theme/catppuccin.css", "./theme/catppuccin-admonish.css"]
